/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/博客复活记': RouteRecordInfo<'/posts/博客复活记', '/posts/博客复活记', Record<never, never>, Record<never, never>>,
    '/posts/初中生活有感': RouteRecordInfo<'/posts/初中生活有感', '/posts/初中生活有感', Record<never, never>, Record<never, never>>,
    '/posts/动态规划': RouteRecordInfo<'/posts/动态规划', '/posts/动态规划', Record<never, never>, Record<never, never>>,
    '/posts/记一次曲折的archLinux虚拟机安装过程': RouteRecordInfo<'/posts/记一次曲折的archLinux虚拟机安装过程', '/posts/记一次曲折的archLinux虚拟机安装过程', Record<never, never>, Record<never, never>>,
    '/posts/解决pnpm找不到GLOBAL_BIN_DIR问题': RouteRecordInfo<'/posts/解决pnpm找不到GLOBAL_BIN_DIR问题', '/posts/解决pnpm找不到GLOBAL_BIN_DIR问题', Record<never, never>, Record<never, never>>,
    '/posts/浅谈IRC': RouteRecordInfo<'/posts/浅谈IRC', '/posts/浅谈IRC', Record<never, never>, Record<never, never>>,
    '/posts/使用教程': RouteRecordInfo<'/posts/使用教程', '/posts/使用教程', Record<never, never>, Record<never, never>>,
    '/posts/图论中的DFS和BFS及其应用': RouteRecordInfo<'/posts/图论中的DFS和BFS及其应用', '/posts/图论中的DFS和BFS及其应用', Record<never, never>, Record<never, never>>,
    '/posts/最短路': RouteRecordInfo<'/posts/最短路', '/posts/最短路', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/hello-world': RouteRecordInfo<'/posts/hello-world', '/posts/hello-world', Record<never, never>, Record<never, never>>,
    '/posts/OI备忘': RouteRecordInfo<'/posts/OI备忘', '/posts/OI备忘', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
